name: Tekkit Permittor
main: thomas15v.main
version: 1.5
  commands:
   tep:
      description: This is a demo command.
#      usage: /<command> [player]
#      permission: <plugin name>.basic
#      permission-message: You don't have <permission>
