name: Tekkit Permittor
main: thomas15v.TekkitPermittor
version: 1.5
commands:
  tep:
    description: This is a demo command.
    usage: /tep [player]
    permission: tekkitpermittor.basic
    permission-message: You don't have tekkitpermittor.basic