name: Tekkit Permittor
main: thomas15v.main
version: 1.3
commands:
  tep:
    description: The command for Tekkit Permitor
    usage: /tep reload
    permission: tekkitpermittor.command
    permission-message: You don't have <permission>
